services:
  - type: web
    name: business-card-website
    env: node
    buildCommand: npm install && npm run build
    startCommand: cd build && node server.js
    envVars:
      - key: NODE_ENV
        value: production 